**Analise de Dados**

In [ ]:
#Importar Bibliotecas: precisa executar todas as vezes que for testar o código
import numpy as np
import pandas as pd
import matplotlib as mp
import matplotlib.pyplot as plt

In [ ]:
#AUTORIZANDO O COLAB para acessar o DRIVE
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#usar arquivo de "Lista de 200 cidades"
df = pd.read_csv("/content/drive/MyDrive/2024_02 Prog Python/ProgPython 8016 ADM/Exercícios e AC's/Lista de 200 cidades.csv")
df

,Índice,Município,População em 2022,Variação absoluta,População em 2010,Taxa de crescimento
0,1,São Paulo (SP),11451245,197742,11253503,1.73%
1,2,Rio de Janeiro (RJ),6211423,-109023,6320446,-1.72%
2,3,Brasília (DF),2817068,244909,2572159,9.52%
3,4,Fortaleza (CE),2428678,-31034,2459712,-1.26%
4,5,Salvador (BA),2418005,-257651,2675656,-9.63%
...,...,...,...,...,...,...
195,196,Mogi Guaçu (SP),153661,16416,137245,11.96%
196,197,Pouso Alegre (MG),152212,21597,130615,16.53%
197,198,Araucária (PR),151666,32543,119123,27.32%
198,199,Alagoinhas (BA),151065,9602,141463,6.79%
199,200,Toledo (PR),15047,31157,119313,26.11%

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Índice               200 non-null    int64
 1   Município            200 non-null    object
 2   População em 2022    200 non-null    int64
 3   Variação absoluta    200 non-null    int64
 4   População em 2010    200 non-null    int64
 5   Taxa de crescimento  200 non-null    object
dtypes: int64(4), object(2)
memory usage: 9.5+ KB

In [ ]:
#Preparando o DF:

df['Taxa de crescimento']=df['Taxa de crescimento'].str.strip('%').astype(float)

df['Cidade']=df['Município'].str.split('(',expand=True)[0]
df['UF']=df['Município'].str.split('(',expand=True)[1].str.strip(')')

df2=df.filter(items=['UF','Cidade', 'População em 2010',
                     'População em 2022', 'Variação absoluta',
                     'Taxa de crescimento'])

df2.head()

,UF,Cidade,População em 2010,População em 2022,Variação absoluta,Taxa de crescimento
0,SP,São Paulo,11253503,11451245,197742,1.73
1,RJ,Rio de Janeiro,6320446,6211423,-109023,-1.72
2,DF,Brasília,2572159,2817068,244909,9.52
3,CE,Fortaleza,2459712,2428678,-31034,-1.26
4,BA,Salvador,2675656,2418005,-257651,-9.63

In [ ]:
#utilizamos esse comando para "PEGAR" os nomes das colunas
df.columns

Index(['Índice', 'Município', 'População em 2022', 'Variação absoluta',
       'População em 2010', 'Taxa de crescimento', 'Cidade', 'UF'],
      dtype='object')

* Q01)  Encontre qual a cidade:
>* de SC que teve a maior Taxa de Crescimento
>* do PA que teve a menor População em 2022
>* quantas cidades (e quais) do RS tiveram a População em 2022, abaixo da média da População em 2022 do PI

In [ ]:
q1_1 = df2['Cidade'].loc[df2['Taxa de crescimento']
                       == df2.where(df2['UF']=='SC')
                       ['Taxa de crescimento'].max()]
q1_1

140    Palhoça
Name: Cidade, dtype: object

In [ ]:
q1_2=df2['Cidade'].loc[df2['População em 2022']
                        == df2.where(df2['UF']=='PA')
                        ['População em 2022'].min()]
q1_2

189    Abaetetuba
Name: Cidade, dtype: object

Nessa aqui temos que testar algumas coisas primeiro...

In [ ]:
df2['Cidade'].loc[df2['População em 2022']
                        < df2.where(df2['UF']=='PI')
                        ['População em 2022'].mean()]

18                     Teresina
23                        Natal
39         Aparecida de Goiânia
57                Montes Claros
73                    Cariacica
95            Juazeiro do Norte
99                        Cotia
101                  Imperatriz
106                    Gravataí
115              Embu das Artes
134                 Sete Lagoas
143                São Leopoldo
153                      Maricá
155    Nossa Senhora do Socorro
157                  Rio Grande
163              Jaraguá do Sul
172                         Itu
187                     Atibaia
190                Itapetininga
191                      Caxias
199                      Toledo
Name: Cidade, dtype: object

In [ ]:
df2['UF'].loc[df2['População em 2022']
                        < df2.where(df2['UF']=='PI')
                        ['População em 2022'].mean()]

18     PI
23     RN
39     GO
57     MG
73     ES
95     CE
99     SP
101    MA
106    RS
115    SP
134    MG
143    RS
153    RJ
155    SE
157    RS
163    SC
172    SP
187    SP
190    SP
191    MA
199    PR
Name: UF, dtype: object

In [ ]:
#Posso usar esse mesmo código para contar quantas cidades do RS: "value_counts()"

df2['UF'].loc[df2['População em 2022']
                        < df2.where(df2['UF']=='PI')
                        ['População em 2022'].mean()].value_counts()

UF
SP    5
RS    3
MG    2
MA    2
PI    1
RN    1
GO    1
ES    1
CE    1
RJ    1
SE    1
SC    1
PR    1
Name: count, dtype: int64

**Precisamos usar "dois filtros" em duas abordagens diferentes:**

* 1o para encontrar quais cidades (linhas) têm essa característica
* 2o para encontrar quais delas são do RS

**... ou ao contrário:**

* 1o para encontrar quais delas são do RS
* 2o para encontrar quais cidades têm essa característica

In [ ]:
#Para encontrar mais "rápido", NÃO vou especificar a coluna do DF2

q1_3a = df2.loc[df2['População em 2022']
                        < df2.where(df2['UF']=='PI')
                        ['População em 2022'].mean()]
q1_3a

,UF,Cidade,População em 2010,População em 2022,Variação absoluta,Taxa de crescimento
18,PI,Teresina,81423,8663,5207,6.39
23,RN,Natal,803739,7513,-52439,-6.52
39,GO,Aparecida de Goiânia,455735,52755,71815,15.76
57,MG,Montes Claros,362148,41424,52092,14.38
73,ES,Cariacica,348738,35351,4772,1.37
95,CE,Juazeiro do Norte,250095,28612,36025,14.40
99,SP,Cotia,20115,27364,7249,36.04
101,MA,Imperatriz,247505,27311,25605,10.35
106,RS,Gravataí,255723,26507,9347,3.66
115,SP,Embu das Artes,24023,25072,1049,4.37
134,MG,Sete Lagoas,214221,22736,13139,6.13
143,RS,São Leopoldo,214087,21741,3323,1.55
153,RJ,Maricá,127397,1973,69903,54.87
155,SE,Nossa Senhora do Socorro,160827,19233,31503,19.59
157,RS,Rio Grande,197228,1919,-5328,-2.70
163,SC,Jaraguá do Sul,143132,18266,39528,27.62
172,SP,Itu,154147,16824,14093,9.14
187,SP,Atibaia,126603,15864,32037,25.31
190,SP,Itapetininga,144377,15779,13413,9.29
191,MA,Caxias,155692,15697,1278,0.82
199,PR,Toledo,119313,15047,31157,26.11

In [ ]:
q1_3b = q1_3a.where(q1_3a['UF']=='RS')['Cidade'].dropna()
q1_3b

106        Gravataí
143    São Leopoldo
157      Rio Grande
Name: Cidade, dtype: object

**Testando a 2a abordagem**

In [ ]:
df_RS = df2.where(df2['UF']=='RS').dropna()
df_RS

,UF,Cidade,População em 2010,População em 2022,Variação absoluta,Taxa de crescimento
10,RS,Porto Alegre,1409351.0,1332570.0,-76781.0,-5.45
47,RS,Caxias do Sul,435551.0,463338.0,27787.0,6.38
78,RS,Canoas,323827.0,347657.0,2383.0,7.36
85,RS,Pelotas,328275.0,325689.0,-2586.0,-0.79
102,RS,Santa Maria,261032.0,271633.0,10601.0,4.06
106,RS,Gravataí,255723.0,26507.0,9347.0,3.66
132,RS,Novo Hamburgo,23894.0,227732.0,-11208.0,-4.69
139,RS,Viamão,239384.0,224116.0,-15268.0,-6.38
143,RS,São Leopoldo,214087.0,21741.0,3323.0,1.55
146,RS,Passo Fundo,184826.0,206224.0,21398.0,11.58
157,RS,Rio Grande,197228.0,1919.0,-5328.0,-2.70
159,RS,Alvorada,195673.0,187315.0,-8358.0,-4.27

In [ ]:
q1_3c = df_RS['Cidade'].loc[df_RS['População em 2022']
                        < df2.where(df2['UF']=='PI')
                        ['População em 2022'].mean()]
q1_3c

106        Gravataí
143    São Leopoldo
157      Rio Grande
Name: Cidade, dtype: object

* Q02) Encontre qual a População em 2010:
>* dessa cidade de SC
>* dessa cidade do PA
>* dessas cidades do MS

In [ ]:
q2_1 = df2['População em 2010'].loc[df2['Taxa de crescimento']
                       == df2.where(df2['UF']=='SC')
                       ['Taxa de crescimento'].max()]
q2_1

140    137334
Name: População em 2010, dtype: int64

In [ ]:
q2_2 = df2['População em 2010'].loc[df2['População em 2022']
                        ==df2.where(df2['UF']=='PA')
                        ['População em 2022'].min()]
q2_2

189    1411
Name: População em 2010, dtype: int64

In [ ]:
#Nesse caso, vou usar o trecho "where+loc" em todo o DF2 e não apenas em uma coluna específica

q2_3a = df2.loc[df2['População em 2022']
                        < df2.where(df2['UF']=='PI')
                        ['População em 2022'].mean()]

In [ ]:
#Esse aqui é um "mini-dataframe" que foi "recortado" do DF2 com os critérios do enunciado

q2_3a

,UF,Cidade,População em 2010,População em 2022,Variação absoluta,Taxa de crescimento
18,PI,Teresina,81423,8663,5207,6.39
23,RN,Natal,803739,7513,-52439,-6.52
39,GO,Aparecida de Goiânia,455735,52755,71815,15.76
57,MG,Montes Claros,362148,41424,52092,14.38
73,ES,Cariacica,348738,35351,4772,1.37
95,CE,Juazeiro do Norte,250095,28612,36025,14.40
99,SP,Cotia,20115,27364,7249,36.04
101,MA,Imperatriz,247505,27311,25605,10.35
106,RS,Gravataí,255723,26507,9347,3.66
115,SP,Embu das Artes,24023,25072,1049,4.37
134,MG,Sete Lagoas,214221,22736,13139,6.13
143,RS,São Leopoldo,214087,21741,3323,1.55
153,RJ,Maricá,127397,1973,69903,54.87
155,SE,Nossa Senhora do Socorro,160827,19233,31503,19.59
157,RS,Rio Grande,197228,1919,-5328,-2.70
163,SC,Jaraguá do Sul,143132,18266,39528,27.62
172,SP,Itu,154147,16824,14093,9.14
187,SP,Atibaia,126603,15864,32037,25.31
190,SP,Itapetininga,144377,15779,13413,9.29
191,MA,Caxias,155692,15697,1278,0.82
199,PR,Toledo,119313,15047,31157,26.11

In [ ]:
q2_3b = q2_3a.where(q2_3a['UF']=='RS')['População em 2010'].dropna()
q2_3b

106    255723.0
143    214087.0
157    197228.0
Name: População em 2010, dtype: float64

In [ ]:
#Poderia escrever "tudo junto", mas fica muito difícil de ler e de entender:

df2.loc[df2['População em 2022']<df2.where(df2['UF']=='PI')['População em 2022'].mean()].where(df2['UF']=='RS')['População em 2010'].dropna()

106    255723.0
143    214087.0
157    197228.0
Name: População em 2010, dtype: float64

## **Porque fui "criando" variáveis ao longo da solução?**

In [ ]:
print(q1_1)
print()
print(q1_2)
print()
print(q1_3b)
print()
print()
print(q2_1)
print()
print(q2_2)
print()
print(q2_3b)

140    Palhoça
Name: Cidade, dtype: object

189    Abaetetuba
Name: Cidade, dtype: object

106        Gravataí
143    São Leopoldo
157      Rio Grande
Name: Cidade, dtype: object


140    137334
Name: População em 2010, dtype: int64

189    1411
Name: População em 2010, dtype: int64

106    255723.0
143    214087.0
157    197228.0
Name: População em 2010, dtype: float64